### ISSUE TITLE
插件如何初始化使用

### ISSUE THREAD

**Issue by DrRyanHuang** [lilith-avatar/vscode-extension#19]
插件如何用啊，球球老铁们来扶贫

是readme里面我看漏了吗，readme说  ”根据工作区打开的文件夹“ , 是打开 smap 文件的意思吗？

VScode安装插件后：
![image](https://user-images.githubusercontent.com/44900829/129544575-4daca575-44a6-410c-a2d0-a7dc6005017d.png)

依然无法打开smap文件

![image](https://user-images.githubusercontent.com/44900829/129544545-b4cb3648-ca74-4d2f-8ca3-29875a34fd6e.png)

**Comment by free-yenyuan** [comment]
你好，你看看有没有Boom!Tree的页签

**Comment by DrRyanHuang** [comment]
@lilith-avatar-yenyuan 
页签是有的，还是打不开诶
![image](https://user-images.githubusercontent.com/44900829/129649744-d09a5c1f-eedd-42ba-b823-e0f27492fc2e.png)

**Comment by DrRyanHuang** [comment]
Hello, 有在跟进嘛？

**Comment by free-yenyuan** [comment]
你好，再次确认了一下，应该是你的工作区中没有从编辑器导出的lua文件，所以不会生成BoomTree哦

**Comment by DrRyanHuang** [comment]
您好，如何 **从编辑器导出lua文件**，menu菜单栏下似乎没有找到
@lilith-avatar-yenyuan 

![image](https://user-images.githubusercontent.com/44900829/129933894-c38b8d4a-4b0b-4f72-9078-fa57c7e68d72.png)

**Comment by free-yenyuan** [comment]
![image](https://user-images.githubusercontent.com/64084912/130002789-dd462dd5-0936-49b5-a1f2-6a5bf6610838.png)
你好，应该是在这里哦

**Comment by DrRyanHuang** [comment]
OK了，感谢

其实可以更新下  README，写一下怎么用这个
